version: '3.8'

services:
  mc-server:
    build: ./docker
    ports:
      - "25565:25565"
    volumes:
      - ../data:/data                 # Синхронизация данных
      - ../backups:/backups            # Локальные бэкапы
    environment:
      EULA: "TRUE"
      JVM_ARGS: "-Xms6G -Xmx9G -Dfml.readTimeout=180"
    stdin_open: true
    tty: true